name: portfolio
description: Portfolio

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  flutter_animate: ^4.3.0
  auto_route: ^8.2.0
  build_runner: ^2.4.11
  auto_route_generator: ^8.0.0
  url_launcher: ^6.3.1
  visibility_detector: ^0.4.0+2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Aboreto
      fonts:
        - asset: assets/Aboreto/Aboreto-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: assets/Montserrat/Montserrat-Regular.ttf
        - asset: assets/Montserrat/Montserrat-Bold.ttf
        - asset: assets/Montserrat/Montserrat-SemiBold.ttf
        - asset: assets/Montserrat/Montserrat-ExtraBold.ttf
        - asset: assets/Montserrat/Montserrat-Light.ttf
        - asset: assets/Montserrat/Montserrat-Medium.ttf

    - family: Shrikhand
      fonts:
        - asset: assets/Shrikhand/Shrikhand-Regular.ttf

